### ISSUE TITLE
Error when looking for gazebo executable in Colab

### ISSUE THREAD

**Issue by flferretti** [ami-iit/rod#32]
Despite having the command `gz sdf --help` working in Colab, when using `rod`, the following error is always raised:

```console
RuntimeError: Failed to find 'sdf' command part of /usr/bin/gz installation.
```

I believe the problem is in these lines:

https://github.com/ami-iit/rod/blob/f63965c479ea37dfd61a4620db4d055cc57fddd8/src/rod/utils/gazebo.py#L28-L32

as by running them in a Colab cell, gives the same exact error. 

Passing the environment variables did not help:

```python
import subprocess
import os

executable = "/usr/bin/gz"
env = os.environ.copy()

cp = subprocess.run([executable, "sdf", "--help"], capture_output=True, env=env)

if cp.returncode != 0:
    msg = f"Failed to find 'sdf' command part of {executable} installation"
    raise RuntimeError(msg)
```

Thanks @xela-95 for raising this up.

**Comment by traversaro** [comment]
Can you report the output of `!apt list --installed` on colab when you are having this problem?

**Comment by flferretti** [comment]
> What is the exit code and stdout/stderr of the `gz sdf --help` when executed in Colab?

```python
Returncode: -11
Stderr: b' gz sdf [options]\n\n\tIntrospect, convert, and output SDF files.\n\tUse the -v option to specify the version of\n\tSDF for use with other options.\n\nOptions:\n  --verbose             Print extra information\n  -h [ --help ]         Print this help message\n  -d [ --describe ]     Print SDF format for given version(-v).\n  -c [ --convert ] arg  In place conversion of arg to the latest SDF version.\n  -o [ --doc ]          Print HTML SDF. Use -v to specify version.\n  -k [ --check ] arg    Validate arg.\n  -v [ --version ] arg  Version of SDF to use with other options.\n  -p [ --print ] arg    Print arg, useful for debugging and as a conversion \n                        tool.\n\n'
Stdout: b''
```

It looks like it is somehow working

**Comment by flferretti** [comment]
I correctly get zero return code when executing the command from a cell:
```sh
!gz sdf --help
!echo "Returncode:" $?

 gz sdf [options]

	Introspect, convert, and output SDF files.
	Use the -v option to specify the version of
	SDF for use with other options.

Options:
  --verbose             Print extra information
  -h [ --help ]         Print this help message
  -d [ --describe ]     Print SDF format for given version(-v).
  -c [ --convert ] arg  In place conversion of arg to the latest SDF version.
  -o [ --doc ]          Print HTML SDF. Use -v to specify version.
  -k [ --check ] arg    Validate arg.
  -v [ --version ] arg  Version of SDF to use with other options.
  -p [ --print ] arg    Print arg, useful for debugging and as a conversion 
                        tool.

Returncode: 0
```

**Comment by traversaro** [comment]
I have a vague feeling that I already experienced this, but I can't remember where.

**Comment by diegoferigo** [comment]
The following code on my machine prints `0`. It's not really clear to me why in Colab calling `gz sdf --help` in such a way does not return 0 as when it's called from bash.

```py
import os
import shutil
import subprocess

gz = shutil.which("gz")
print(subprocess.run([gz, "sdf", "--help"], capture_output=True, env=os.environ).returncode)
```

What about running in a cell:

```
!bash -c 'gz sdf --help >/dev/null && echo $?'
```

**Comment by diegoferigo** [comment]
Btw I'm not sure that the following returns what expected:

```
!gz sdf --help
!echo "Returncode:" $?
```

The return code is not the one of the first command.

**Comment by flferretti** [comment]
> What about running in a cell:

> !bash -c 'gz sdf --help >/dev/null && echo $?'


```sh
 gz sdf [options]

	Introspect, convert, and output SDF files.
	Use the -v option to specify the version of
	SDF for use with other options.

Options:
  --verbose             Print extra information
  -h [ --help ]         Print this help message
  -d [ --describe ]     Print SDF format for given version(-v).
  -c [ --convert ] arg  In place conversion of arg to the latest SDF version.
  -o [ --doc ]          Print HTML SDF. Use -v to specify version.
  -k [ --check ] arg    Validate arg.
  -v [ --version ] arg  Version of SDF to use with other options.
  -p [ --print ] arg    Print arg, useful for debugging and as a conversion 
                        tool.

bash: line 1: 27207 Segmentation fault      (core dumped) gz sdf --help > /dev/null
```

**Comment by diegoferigo** [comment]
Here we go, something is wrong there. I now have some memory as well of this segmentation fault. I believe the non-zero return code is related to this.

**Comment by traversaro** [comment]
Probably we can mention that colab is not supported in jaxsim docs (or at least not mention colab?).

**Comment by diegoferigo** [comment]
> Probably we can mention that colab is not supported in jaxsim docs (or at least not mention colab?).

The main problem here is that calling `gz sdf` segfaults in the default installation of Colab. Somewhere you posted that Colab is about to get an upgraded OS around April / May, but I cannot find the link. Maybe the problem will get fixed there?

Alternatively, I'd be in favor of a temporarily workaround in rod for ignoring the non-zero exit code corresponding to the segmentation fault.

**Comment by traversaro** [comment]
> Somewhere you posted that Colab is about to get an upgraded OS around April / May, but I cannot find the link.

Note sure about this, but it seems that Colab updates its Ubuntu distro to the latest LTS after several months, see:
* Update to 22.04 done on 23.09 https://medium.com/google-colab/colab-updated-to-ubuntu-22-04-lts-709a91555b3c
* Update to 20.04 done on 23.01 https://medium.com/google-colab/colab-updated-to-ubuntu-20-04-lts-d34112d6eb10

So I am not sure if they update anytime to 24.04 LTS. Furthermore, note that on Ubuntu 24.04 there is no Gazebo Classic apt binary.

**Comment by traversaro** [comment]
As I guess no one is going to work on this in the short term, could it make sense to remove the colab references from the jaxsim docs? fyi @diegoferigo @flferretti @lorycontixd @xela-95 @CarlottaSartore @S-Dafarra

**Comment by flferretti** [comment]
Yes, it makes sense. I'll handle this

**Comment by diegoferigo** [comment]
These days I'm working on `rod` for few fixes needed by JaxSim. Given that Gazebo/sdformat is no longer present in the official repos of Ubuntu starting from 24.04, I was thinking to require users to install sdformat and gz-tools (to have the `gz` commandline) from either the custom PPA or from conda.

Have anyone ever tried if the problem persists also when we use the `gz` command from the PPA?

**Comment by diegoferigo** [comment]
We should try again by installing one of the working configurations from the OSRF PPA as discussed in https://github.com/ami-iit/rod/pull/34#issuecomment-2116915112. The current minimum requirement is `libsdformat13 gz-tools2`.

**Comment by diegoferigo** [comment]
@flferretti is this issue solved now that we updated the minimum version of sdformat in #34?

**Comment by flferretti** [comment]
Yes, this has been fixed. Thanks!

Closing
