### ISSUE TITLE
Loading a URDF fail if `LD_DEBUG=libs` is set in the env variable

### ISSUE THREAD

**Issue by traversaro** [ami-iit/rod#52]
If I set `LD_DEBUG=libs` is set, the loading of URDF file is failing with error:

~~~
ImportError while loading conftest '/home/straversaro-iit.local/jaxsim/tests/conftest.py'.
tests/conftest.py:6: in <module>
    import rod
.pixi/envs/tasks-gpu/lib/python3.12/site-packages/rod/__init__.py:136: in <module>
    check_compatible_sdformat(specification_version="1.10")
.pixi/envs/tasks-gpu/lib/python3.12/site-packages/rod/__init__.py:123: in check_compatible_sdformat
    xmltodict.parse(
.pixi/envs/tasks-gpu/lib/python3.12/site-packages/xmltodict.py:359: in parse
    parser.Parse(xml_input, True)
E   xml.parsers.expat.ExpatError: junk after document element: line 2, column 3
~~~

This is a problem of using an external program instead of a proper library (see https://github.com/ami-iit/rod/issues/30). It may be possible to mitigate/solve the problem by only considering the stdout output instead of the stderr, but I did not checked.

**Comment by flferretti** [comment]
Thanks @traversaro for reporting this! Can you try if the modifications of https://github.com/ami-iit/rod/pull/53 fix that issue?
