### ISSUE TITLE
Implement logic to resolve resources URIs

### ISSUE THREAD

**Issue by diegoferigo** [ami-iit/rod#8]
SDF files could use different special tags to access resources from the file system without using absolute paths:

- Model composition: http://sdformat.org/tutorials?tut=composition
- Gazebo's environment variables: https://classic.gazebosim.org/tutorials?tut=components&cat=get_started

There's always been some confusion (at least in my case) to figure out what is the correct environment variable and URI to use. For example, [this is](https://github.com/robotology/gym-ignition-models/tree/088a81c55970ca5eec51108d249b8ce3dfd09e7a#standalone-usage) what I ended up implementing in gym-ignition-models, and [this is](https://github.com/robotology/icub-models/tree/0b3b819a0423454ff19cff136cfd2b1f7c307347#use-the-models-with-gazebo) the configuration of icub-models.

Furthermore, URDF to SDF conversion could still be affected by https://github.com/gazebosim/sdformat/issues/227, but I didn't try recently if it was fixed.

This being said, we could implement a pretty extensive logic to resolve all the combinations. I already ended up implementing a work around in a [downstream library](https://github.com/ami-iit/meshcat-viz-python/blob/9cc3a7c885e860d8601b37f2f2c3d46d292e2c4f/src/meshcat_viz/model_builder.py#L56-L85), that could be ported here in `rod`.

**Comment by diegoferigo** [comment]
As written in https://github.com/ami-iit/rod/pull/20#issuecomment-1423886461, we should properly understand all the URI combinations and support all of them. That PR only provides an initial support.

**Comment by diegoferigo** [comment]
The logic include in `rod` has been extended by @traversaro in https://github.com/ami-iit/resolve-robotics-uri-py. We might add add this new external dependency if we want a more extensive URI support.

**Comment by traversaro** [comment]
> The logic included in `rod` has been extended by @traversaro in https://github.com/ami-iit/resolve-robotics-uri-py. We might add add this new external dependency if we want a more extensive URI support.

That may be a good idea, so that if we want to add other kind of support, we can do that. Ideally we can also look into supporting fuel or other fancy, start, by lazy loading sdformat python bindings.

**Comment by diegoferigo** [comment]
Early support was introduced in #20 and finalized in #28. Closing.
